language: ruby
rvm:
  - 2.6.4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - bundle install
  - yarn install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - nvm use $NODE_VERSION
  - bundle exec rspec
services:
  - postgresql
env:
  global:
    - NODE_VERSION=9.3.0
    - STRAVA_CLIENT_ID=clientid
    - STRAVA_CLIENT_SECRET=clientsecret
    - BASE_URL=http://test.localhost
notifications:
  email: false
